### ISSUE TITLE
Nevalidní XML pokud název obsahuje uvozovky

### ISSUE THREAD

**Issue by dfiser** [edesky/edesky_api#3]
Aplikace generuej nevalidní URL, pokud název dokumentu (případně i jiná pole) obsahuje znak uvozovky. Příklad z URL "view-source:https://edesky.cz/api/v1/documents?created_from=2017-01-28&dashboard_id=65&order=date&search_with=sql&page=1":

`<document created_at='2017-02-08 17:11:25 +0100' dashboard_category='samosprava' dashboard_id='65' dashboard_name='Město Jindřichův Hradec' dashboard_ovm_ico='246875' dashboard_ovm_zkratka='JINDHRAD' dashboard_ruian_kod='545881' edesky_id='634648' edesky_text_url='https://edesky.cz/dokument/634648.txt' edesky_url='https://edesky.cz/dokument/634648' name='KÚ  Jihočeský kraj - Rozhodnutí - "Obnova rybníka Blatec" k.ú. Příbraz' orig_url='http://www.jh.cz/redakce/index.php?lanG=cs&amp;clanek=50569&amp;slozka=48383&amp;xsekce=50568&amp;as4uOriginalDomain=www.jh.cz&amp;detail_claim=71225&amp;'>`

Takovýto XML dokument pak nelze dále parsovat. Nahraďte prosím znak " entitou `&quot;` ve všech textech z úřední desky.

**Comment by aufi** [comment]
Dobrý den, díky za zprávu. Pokud je mi známo, generovaný výstup *je validní* (hodnoty atributů jsou obaleny znakem ' a potom nevidím ve znaku " uvnitř problém).

Můžu požádat o bližší informace, jak parsování XML selhává - z online validátoru [1] jsem nebyl schopen chybu navodit, díky.

[1] https://www.xmlvalidation.com/

**Comment by dfiser** [comment]
Dobrý den,

omlouvám se, máte pravdu. Problém byl způsoben tím, že jsem si 
požadovaný XML dokument otevřel ve Firefoxu, kde jsem si ho uložil pro 
prvotní vývoj mého nástroje na stažení info o vybrané úřední desce.

Jakmile jsem XML načítal přímo z aplikace, bylo vše v pořádku a XML bylo 
validní.

Problém tedy byl způsoben úpravou původního XML ve Firefoxu a nejde o 
chybu ve Vašem rozhraní.

Díky za skvělé API!

S pozdravem
Daniel Fišer


Marek Aufart wrote on 2017-02-12 at 17:48 CET:

**Comment by aufi** [comment]
Děkuji, jsem rád, že to funguje.
